cache: {}

stages:
  - test
  - dockerize

lint:
  stage: test
  image: node:8-alpine
  script:
    - yarn --ignore-engines
    - yarn lint

unit_test:
  stage: test
  image: node:8-alpine
  script:
    - yarn --ignore-engines
    - yarn test

e2e_test:
  stage: test
  image: cypress/base:8
  script:
    - yarn --ignore-engines
    - yarn e2e:ci
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - package.json
      - Dockerfile
      - ./dist

dockerize:
  stage: dockerize
  image: docker:latest
  when: on_success
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none
  only:
    - master
  script:
    - ls -ltr
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.com/unicron-lab
    - docker build -t registry.gitlab.com/unicron-lab/unicron-ui:$CI_JOB_ID .
    - docker push registry.gitlab.com/unicron-lab/unicron-ui
