language: node_js
node_js:
  - '8'
services:
  - docker
install:
  - yarn --ignore-engines
  - yarn test
  - yarn e2e:ci
  - yarn build
  - docker build -t turbologz/turbo-logz-ui:$TRAVIS_BUILD_NUMBER .
deploy:
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push turbologz/turbo-logz-ui
    on:
      branch: master
